name: Continuous Integration - Open PR - Workflow

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!homolog'
      - '!dev'

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: Automated PR creation'
          title: 'Automated PR for new feature'
          body: |
            This PR was automatically created by GitHub Actions on a push to a feature branch.
            Please review the changes.
          branch: ${{ github.ref_name }}
          base: dev