name: Continuous Integration - Open PR - Workflow

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!homolog'
      - '!dev'

jobs:
  Create-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: Automated PR creation'
          title: 'Automated PR'
          body: |
            This PR was automatically created by GitHub Actions on a push to a project branch.
            Please review the changes.
          branch: ${{ github.ref_name }}
          base: dev