name: Continuous Integration - Open PR - Workflow

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!homolog'
      - '!dev'

permissions:
  contents: write
  pull-requests: write
jobs:
  Create_PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr create --title "PR TESTE" --body "CORPO DO PR TESTE" --base dev