name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - dev
      - homolog
      - main

jobs:
  CI_snowflake:
    name: 'Run validation'
    defaults:
      run:
        shell: bash
        
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4

    - name: 'Get changed files'
      id: changed-files
      uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
      # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
      # with:
      #   since_last_remote_commit: true 

    - name: 'List all changed files'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      
    - name: 'Install Python'
      uses: actions/setup-python@v6
      with:
        python-version: '3.13' 

    - name: 'Run Validation Script'
      run: python .github/validation_scripts/validate.py {{ env.ALL_CHANGED_FILES }}

  # changed_files:
  #   runs-on: ubuntu-latest
  #   name: Test changed-files
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Get changed files
  #       id: changed-files
  #       uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
  #       # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
  #       # with:
  #       #   since_last_remote_commit: true 

  #     - name: List all changed files
  #       env:
  #         ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}

